.TH "VierGewinnt.Form2.Spielfeldtile" 3 "Wed Jun 16 2021" "VierGewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VierGewinnt.Form2.Spielfeldtile
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBiwidth\fP"
.br
.ti -1c
.RI "int \fBiheight\fP"
.br
.ti -1c
.RI "string \fBfarbe\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VierGewinnt from the source code\&.
