.TH "VierGewinnt.Form3.Spielfeldtile" 3 "Wed Jun 16 2021" "VierGewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VierGewinnt.Form3.Spielfeldtile \- Struct woraus das spielfeld erstellt wird mit den posotionen und der Frabe Des dort liegenden steins  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.RI "Die X und Y achsen Und Die Pixel Hühe und Breite Des Steins "
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBiwidth\fP"
.br
.ti -1c
.RI "int \fBiheight\fP"
.br
.ti -1c
.RI "string \fBfarbe\fP"
.br
.RI "Farbe des Steins Weis -> Nix "
.in -1c
.SH "Detailed Description"
.PP 
Struct woraus das spielfeld erstellt wird mit den posotionen und der Frabe Des dort liegenden steins 


.SH "Member Data Documentation"
.PP 
.SS "string VierGewinnt\&.Form3\&.Spielfeldtile\&.farbe"

.PP
Farbe des Steins Weis -> Nix 
.SS "int VierGewinnt\&.Form3\&.Spielfeldtile\&.x"

.PP
Die X und Y achsen Und Die Pixel Hühe und Breite Des Steins 

.SH "Author"
.PP 
Generated automatically by Doxygen for VierGewinnt from the source code\&.
