.TH "VierGewinnt.Form3" 3 "Wed Jun 16 2021" "VierGewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VierGewinnt.Form3
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSpielfeldtile\fP"
.br
.RI "Struct woraus das spielfeld erstellt wird mit den posotionen und der Frabe Des dort liegenden steins "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm3\fP ()"
.br
.RI "Beim Inizialisieren Von Form 3 "
.ti -1c
.RI "string \fBStartListening\fP (string Senden)"
.br
.ti -1c
.RI "string \fBStartClient\fP (string Senden)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSpielfeldtile\fP[,] \fBspielfelder\fP"
.br
.RI "Erstellt aus dem struct \fBSpielfeldtile\fP ein "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static ManualResetEvent \fBEmpfangenSignal\fP = new ManualResetEvent(false)"
.br
.RI "Signaliseirt Den Task/Threads ob was Empfangen wurde damit sie nicht mehr wartenüssen "
.ti -1c
.RI "static ManualResetEvent \fBMeinZugSignal\fP = new ManualResetEvent(false)"
.br
.RI "Mein Zug Signalisert wann Der Eigene Zug Zuendet ist undnicht mehr darauf gewartet werden muss Das man sein zug macht "
.ti -1c
.RI "static int \fBiSpielfeldheight\fP = 4"
.br
.RI "Die Spielfeld Höhe Standart ist Vier Wird Vor Aufruf Von \fBForm3\fP Von \fBForm1\fP Festgelget "
.ti -1c
.RI "static int \fBiSpielfeldwidth\fP = 4"
.br
.RI "Die Spielfeld breite Standart ist Vier Wird Vor Aufruf Von \fBForm3\fP Von \fBForm1\fP Festgelget "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClosed\fP (EventArgs e)"
.br
.RI "Wenn Man Das Fenster Schliest Sorgt dies Dafür das Alles geschlossen wird auch wenn noch die suche läuft oder ein Task/Thread hintergrund wartet und diese auch beendet werden Es wird eine message box Angezeigt die sagt das Das Programm beendet wurde "
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VierGewinnt\&.Form3\&.Form3 ()"

.PP
Beim Inizialisieren Von Form 3 Array Von Endpoinst Difiniert Die Bei Der Suche Nach Diesen Gefüllt wird Momentan wird davon ausgegangen das im gleichen Netztwerk nicht mehr als 10 sind
.PP
Window Pratmeter wie Window state maximise box -> ob man das Fenster vergrößern kann
.PP
die Größe Der Pixel Von den Federn X und Y
.PP
Die Bitmap Frame Wird Definiert
.PP
Die Bitmap Wird mit der Hintergrund farbe gefüllt
.PP
Das Switch Case Legt Die Gewinnummer Fest Auf Der Bsis Was man In \fBForm1\fP Eingegeben hat Der Default ist 4 Eher Ein Easter Egg da es nicht gesagt wird das Man Die Gewinnummer Änder kann
.PP
Am Ende Wird nach der Inizialisertung Noch die Ip Des Pc abgefragt und angezeigt Es Wird immer Die erste IP genommen auch wenn er mehr findet nimmt er immer die erste
.SH "Member Function Documentation"
.PP 
.SS "override void VierGewinnt\&.Form3\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "override void VierGewinnt\&.Form3\&.OnClosed (EventArgs e)\fC [protected]\fP"

.PP
Wenn Man Das Fenster Schliest Sorgt dies Dafür das Alles geschlossen wird auch wenn noch die suche läuft oder ein Task/Thread hintergrund wartet und diese auch beendet werden Es wird eine message box Angezeigt die sagt das Das Programm beendet wurde 
.SH "Member Data Documentation"
.PP 
.SS "ManualResetEvent VierGewinnt\&.Form3\&.EmpfangenSignal = new ManualResetEvent(false)\fC [static]\fP"

.PP
Signaliseirt Den Task/Threads ob was Empfangen wurde damit sie nicht mehr wartenüssen 
.SS "int VierGewinnt\&.Form3\&.iSpielfeldheight = 4\fC [static]\fP"

.PP
Die Spielfeld Höhe Standart ist Vier Wird Vor Aufruf Von \fBForm3\fP Von \fBForm1\fP Festgelget 
.SS "int VierGewinnt\&.Form3\&.iSpielfeldwidth = 4\fC [static]\fP"

.PP
Die Spielfeld breite Standart ist Vier Wird Vor Aufruf Von \fBForm3\fP Von \fBForm1\fP Festgelget 
.SS "ManualResetEvent VierGewinnt\&.Form3\&.MeinZugSignal = new ManualResetEvent(false)\fC [static]\fP"

.PP
Mein Zug Signalisert wann Der Eigene Zug Zuendet ist undnicht mehr darauf gewartet werden muss Das man sein zug macht 
.SS "\fBSpielfeldtile\fP [,] VierGewinnt\&.Form3\&.spielfelder"

.PP
Erstellt aus dem struct \fBSpielfeldtile\fP ein 

.SH "Author"
.PP 
Generated automatically by Doxygen for VierGewinnt from the source code\&.
