.TH "VierGewinnt.Form2" 3 "Wed Jun 16 2021" "VierGewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VierGewinnt.Form2
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSpielfeldtile\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm2\fP (bool _Fullscreen)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSpielfeldtile\fP[,] \fBspielfelder\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBiSpielfeldheight\fP = 4"
.br
.ti -1c
.RI "static int \fBiSpielfeldwidth\fP = 4"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClosed\fP (EventArgs e)"
.br
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void VierGewinnt\&.Form2\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for VierGewinnt from the source code\&.
